# Generated by Django 4.0.1 on 2022-02-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_project_category_delete_catergory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('place', models.CharField(blank=True, max_length=10000, null=True)),
                ('date', models.CharField(blank=True, max_length=10000, null=True)),
                ('paper_url', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
